


/**
 * hot news list request
 */
export const REQUEST_HOTNEWS_LIST = 'REQUEST_HOTNEWS_LIST';
export const FETCH_HOTNEWS_LIST = 'FETCH_HOTNEWS_LIST';
export const RECEIVE_HOTNEWS_LIST = 'RECEIVE_HOTNEWS_LIST';

/**
 * latest news list request
 */
export const REQUEST_LATESTNEWS_LIST = 'REQUEST_LATESTNEWS_LIST';
export const FETCH_LATESTNEWS_LIST = 'FETCH_LATESTNEWS_LIST';
export const RECEIVE_LATESTNEWS_LIST = 'RECEIVE_LATESTNEWS_LIST';

export const REQUEST_BEFORENEWS_LIST = 'REQUEST_BEFORENEWS_LIST';
export const FETCH_BEFORENEWS_LIST = 'FETCH_BEFORENEWS_LIST';
export const RECEIVE_BEFORENEWS_LIST = 'RECEIVE_BEFORENEWS_LIST';

/**
 * details request
 */
export const REQUEST_DETAILS_LIST = 'REQUEST_DETAILS_LIST';
export const FETCH_DETAILS_LIST = 'FETCH_DETAILS_LIST';
export const RECEIVE_DETAILS_LIST = 'RECEIVE_DETAILS_LIST';

