


/**
 * hot news list request
 */
export const REQUEST_HOTNEWS_LIST = 'REQUEST_HOTNEWS_LIST';
export const FETCH_HOTNEWS_LIST = 'FETCH_HOTNEWS_LIST';
export const RECEIVE_HOTNEWS_LIST = 'RECEIVE_HOTNEWS_LIST';

/**
 * last news list request
 */
export const REQUEST_LASTNEWS_LIST = 'REQUEST_LASTNEWS_LIST';
export const FETCH_LASTNEWS_LIST = 'FETCH_LASTNEWS_LIST';
export const RECEIVE_LASTNEWS_LIST = 'RECEIVE_LASTNEWS_LIST';

/**
 * details request
 */
export const REQUEST_DETAILS_LIST = 'REQUEST_DETAILS_LIST';
export const FETCH_DETAILS_LIST = 'FETCH_DETAILS_LIST';
export const RECEIVE_DETAILS_LIST = 'RECEIVE_DETAILS_LIST';

