


/**
 * zhihu request
 */
export const REQUEST_ZHIHU_NEWS_LIST = 'REQUEST_ZHIHU_NEWS_LIST';
export const FETCH_ZHIHU_NEWS_LIST = 'FETCH_ZHIHU_NEWS_LIST';
export const RECEIVE_ZHIHU_NEWS_LIST = 'RECEIVE_ZHIHU_NEWS_LIST';





